# -*- coding: utf-8 -*-
"""task2.1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/177hlJAV2C_ocBbApaCmS5agyHZ87ENVe
"""

#!/usr/bin/env python3
from ev3dev.ev3 import LargeMotor
from ev3dev2.power import PowerSupply
import time
import os
import shutil
import math
# Класс для получения данных о заряде батареи
volts = PowerSupply()
# Класс для взаимодействия с двигателем
motorA = LargeMotor('outA')

# Создаем папочку для данных
if os.path.exists('/home/robot/task2.3'):#проверяет есть ли такой путь
    shutil.rmtree('/home/robot/task2.3') #удаление папки

os.makedirs('/home/robot/task2.3')#cоздание папки
k_p = 0.5#!!!!!!!нужно для трех разных k снять, меняем к - > меняем в названии файла значение k
k_i=0.5
theta_max = 0
error_last_1=0
error_last_2=0
error_last_3=0
u_last_1 = 0
u_last_2=0
u_last_3=0
try:
     # Сохраняем начальное время
    start_time = time.time()
    # Сохраняем начальную позицию
    motorA.position=0
    # В течение двух секунд записываем в файл данные в формате: <time,angle>
    while (time.time() - start_time) < 2:
        theta = motorA.position
        # Подаем на мотор напряжение U
        t=time.time()
        g=3*sin(motorA.speed*t+1)+2*cos(motorA.speed*t)
        er = g - theta
        delta_t =time.time-t_last

        D =1/delta_t**3 - 5/delta_t**2 + 1/delta_t - 5
        A=(3*u_last_1 - 3*u_last_2 + u_last_3)/(delta_t**3*D)
        B=5*(-2*u_last_1+u_last_2)/(D*(delta_t**2))
        C=u_last_1/(delta_t*D)

        E1=2.95*(er-3*error_last_1 + 3 * error_last_2 - error_last_3)/delta_t**3
        E2=0.25*(er-2*error_last_1 + error_last_2)/delta_t**2
        E3=2.75*(er-error_last_1)/delta_t
        E=E1+E2+E3+0.05*er
        U = A+B+C+E/D
        motorA.run_direct(duty_cycle_sp=U)
        error_last_1 = er
        error_last_2 = error_last_1
        error_last_3 = error_last_2
        u_last_1 = U
        u_last_2 = u_last_1
        u_last_3 = u_last_2
        t_last=time.time
        if motorA.position > theta_max:
            theta_max = motorA.position
            # Конструкция 'with open() as f' означает то же самое, что и 'f = open(); ...; f.close()'
            with open('task2.3') as f:
                print(str(time.time() - start_time) + ',' + str(theta))
                f.write(str(time.time() - start_time) + ',' + str(theta) + '\n')
        else:
            f.write("\nError is" + str(error))
    # Останавливаем мотор
    motorA.run_direct(duty_cycle_sp=0)
    time.sleep(1)
except Exception as e:
    raise e
finally:
    # Останавливаем мотор в случае ошибок в коде
    motorA.stop(stop_action='brake')

# Выводим заряд батареи, то есть реальное напряжение в вольтах, которое подается на двигатель при 100% поданной на него мощности
print("Volts: " + str(volts.measured_volts))

